### ISSUE TITLE
[Doc] Indicate the link to the open benchmark dataset in the README

### ISSUE THREAD

**Issue by tvercaut** [charliebudd/torch-content-area#18]
https://www.synapse.org/#!Synapse:syn32148000 or ideally a minted doi

**Comment by charliebudd** [comment]
Linked to GitHub repo of the python loader for dataset [https://github.com/charliebudd/eca-dataset](https://github.com/charliebudd/eca-dataset) which in turn links to the synapse dataset via a doi [https://doi.org/10.7303/syn32148000](https://doi.org/10.7303/syn32148000)
